server:
  port: 8080
  servlet:
    context-path: /api

spring:
  profiles:

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
    schema: classpath*:sql/local/schema.sql
    data: classpath*:sql/local/data.sql
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
